services:
  react:
    build: ./frontend
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    depends_on:
      - node-server
    volumes:
      - ./frontend:/src
      - ignore:/src/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
      - WATCHPACK_POLLING=true

  node-server:
    build: ./backend
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/src
      - ignore:/src/node_modules

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./conf:/etc/nginx/conf.d/

volumes:
  ignore: